{{-- Komponen ikon bersama untuk tampilan publik dan panel admin. --}}
@props(['name', 'size' => 20])

@php
    $bootstrapIcons = [
        'activity' => 'graph-up-arrow',
        'arrow-left' => 'arrow-left',
        'arrow-right' => 'arrow-right',
        'arrow-up' => 'arrow-up',
        'award' => 'award',
        'bullhorn' => 'megaphone',
        'calendar' => 'calendar3',
        'camera' => 'camera',
        'chart' => 'bar-chart',
        'class-promotion' => 'bar-chart',
        'chevron-left' => 'chevron-left',
        'chevron-down' => 'chevron-down',
        'chevron-right' => 'chevron-right',
        'circle' => 'circle-fill',
        'classes' => 'calendar3',
        'clock' => 'clock',
        'csv' => 'filetype-csv',
        'dashboard' => 'columns-gap',
        'edit' => 'pencil-square',
        'ekstrakurikuler' => 'joystick',
        'envelope' => 'envelope',
        'envelope-open' => 'envelope-open',
        'external' => 'box-arrow-up-right',
        'eye' => 'eye',
        'eye-off' => 'eye-slash',
        'facebook' => 'facebook',
        'file-image' => 'file-earmark-image',
        'folder-open' => 'folder2-open',
        'graduation' => 'mortarboard',
        'guru_staff' => 'person-vcard',
        'help' => 'question-circle',
        'image' => 'image',
        'info' => 'info-circle',
        'instagram' => 'instagram',
        'journal' => 'journal',
        'logout' => 'box-arrow-right',
        'map-pin' => 'geo-alt',
        'menu' => 'list',
        'message' => 'chat-left-text',
        'chatbot-faq' => 'robot',
        'moon' => 'moon',
        'news' => 'newspaper',
        'palette' => 'palette',
        'people' => 'people',
        'person-badge' => 'person-badge',
        'person-circle' => 'person-circle',
        'phone' => 'telephone',
        'phone-out' => 'telephone-outbound',
        'plus' => 'plus-lg',
        'pulse' => 'activity',
        'refresh' => 'arrow-clockwise',
        'save' => 'floppy',
        'school' => 'building',
        'search' => 'search',
        'settings' => 'gear',
        'sidebar-close' => 'layout-sidebar-inset',
        'sidebar-open' => 'layout-sidebar-inset-reverse',
        'stars' => 'stars',
        'students' => 'people',
        'tiktok' => 'tiktok',
        'toggle-off' => 'toggle-off',
        'toggle-on' => 'toggle-on',
        'trash' => 'trash',
        'trending-up' => 'graph-up-arrow',
        'user' => 'person',
        'user-shield' => 'shield-check',
        'users-slash' => 'person-x',
        'warning' => 'exclamation-triangle',
        'x' => 'x-lg',
        'youtube' => 'youtube',
    ];

    $icon = $bootstrapIcons[$name] ?? 'circle';
@endphp

<svg {{ $attributes->merge([
    'width' => $size,
    'height' => $size,
    'viewBox' => '0 0 16 16',
    'fill' => 'currentColor',
    'aria-hidden' => 'true',
]) }}>
    <use href="{{ asset('assets/bootstrap-icons.svg') }}#{{ $icon }}"/>
</svg>
