<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Istilah yang kapitalisasinya harus dipertahankan
    |--------------------------------------------------------------------------
    |
    | Tambahkan singkatan, nama lembaga, atau istilah khas sekolah di sini.
    | Kunci wajib ditulis dengan huruf kecil.
    |
    */
    'terms' => [
        'sd' => 'SD',
        'smp' => 'SMP',
        'sma' => 'SMA',
        'smk' => 'SMK',
        'diy' => 'DIY',
        'ipm' => 'IPM',
        'hw' => 'HW',
        'nu' => 'NU',
        'ri' => 'RI',
        'ai' => 'AI',
        'tik' => 'TIK',
        'it' => 'IT',
        'sdm' => 'SDM',
        'ukm' => 'UKM',
        'jl' => 'Jl',
        'jln' => 'Jln',
        'no' => 'No',
        'km' => 'Km',
        'rt' => 'RT',
        'rw' => 'RW',
        'senin' => 'Senin',
        'selasa' => 'Selasa',
        'rabu' => 'Rabu',
        'kamis' => 'Kamis',
        'jumat' => 'Jumat',
        'jum’at' => 'Jum’at',
        'sabtu' => 'Sabtu',
        'minggu' => 'Minggu',
        'januari' => 'Januari',
        'februari' => 'Februari',
        'maret' => 'Maret',
        'april' => 'April',
        'mei' => 'Mei',
        'juni' => 'Juni',
        'juli' => 'Juli',
        'agustus' => 'Agustus',
        'september' => 'September',
        'oktober' => 'Oktober',
        'november' => 'November',
        'desember' => 'Desember',
        'al-qur’an' => 'Al-Qur’an',
        'al-quran' => 'Al-Qur’an',
        'muhammadiyah' => 'Muhammadiyah',
        'kolombo' => 'Kolombo',
    ],

    /*
    |--------------------------------------------------------------------------
    | Gelar akademik dan vokasi yang tidak ambigu
    |--------------------------------------------------------------------------
    |
    | Daftar ini hanya digunakan setelah koma pada nama. Gelar depan dan gelar
    | profesi yang dapat berubah makna karena kapitalisasi tidak dimasukkan.
    |
    */
    'academic_degrees' => [
        // Diploma dan vokasi
        'a.p.' => 'A.P.',
        'a.ma.' => 'A.Ma.',
        'a.md.' => 'A.Md.',
        'a.md.ak.' => 'A.Md.Ak.',
        'a.md.bns.' => 'A.Md.Bns.',
        'a.md.farm.' => 'A.Md.Farm.',
        'a.md.fis.' => 'A.Md.Fis.',
        'a.md.gz.' => 'A.Md.Gz.',
        'a.md.keb.' => 'A.Md.Keb.',
        'a.md.kep.' => 'A.Md.Kep.',
        'a.md.kes.' => 'A.Md.Kes.',
        'a.md.kom.' => 'A.Md.Kom.',
        'a.md.li.' => 'A.Md.Li.',
        'a.md.par.' => 'A.Md.Par.',
        'a.md.per.' => 'A.Md.Per.',
        'a.md.pjk.' => 'A.Md.Pjk.',
        'a.md.rmik.' => 'A.Md.RMIK.',
        'a.md.ro.' => 'A.Md.RO.',
        's.tr.ak.' => 'S.Tr.Ak.',
        's.tr.bns.' => 'S.Tr.Bns.',
        's.tr.farm.' => 'S.Tr.Farm.',
        's.tr.ftr.' => 'S.Tr.Ftr.',
        's.tr.gz.' => 'S.Tr.Gz.',
        's.tr.ip.' => 'S.Tr.IP.',
        's.tr.keb.' => 'S.Tr.Keb.',
        's.tr.kep.' => 'S.Tr.Kep.',
        's.tr.kes.' => 'S.Tr.Kes.',
        's.tr.kom.' => 'S.Tr.Kom.',
        's.tr.li.' => 'S.Tr.Li.',
        's.tr.log.' => 'S.Tr.Log.',
        's.tr.m.' => 'S.Tr.M.',
        's.tr.par.' => 'S.Tr.Par.',
        's.tr.p.' => 'S.Tr.P.',
        's.tr.pi.' => 'S.Tr.Pi.',
        's.tr.pt.' => 'S.Tr.Pt.',
        's.tr.rmik.' => 'S.Tr.RMIK.',
        's.tr.sn.' => 'S.Tr.Sn.',
        's.tr.sos.' => 'S.Tr.Sos.',
        's.tr.t.' => 'S.Tr.T.',

        // Sarjana
        's.a.b.' => 'S.A.B.',
        's.a.bsy.' => 'S.A.Bsy.',
        's.ag.' => 'S.Ag.',
        's.ak.' => 'S.Ak.',
        's.akt.' => 'S.Akt.',
        's.ant.' => 'S.Ant.',
        's.ars.' => 'S.Ars.',
        's.ds.' => 'S.Ds.',
        's.e.' => 'S.E.',
        's.farm.' => 'S.Farm.',
        's.fil.' => 'S.Fil.',
        's.gz.' => 'S.Gz.',
        's.h.' => 'S.H.',
        's.han.' => 'S.Han.',
        's.hum.' => 'S.Hum.',
        's.hut.' => 'S.Hut.',
        's.i.kom.' => 'S.I.Kom.',
        's.i.p.' => 'S.I.P.',
        's.ked.' => 'S.Ked.',
        's.ked.g.' => 'S.Ked.G.',
        's.kep.' => 'S.Kep.',
        's.kes.' => 'S.Kes.',
        's.k.h.' => 'S.K.H.',
        's.k.m.' => 'S.K.M.',
        's.kom.' => 'S.Kom.',
        's.mat.' => 'S.Mat.',
        's.m.' => 'S.M.',
        's.p.' => 'S.P.',
        's.pd.' => 'S.Pd.',
        's.pd.i.' => 'S.Pd.I.',
        's.pi.' => 'S.Pi.',
        's.psi.' => 'S.Psi.',
        's.pt.' => 'S.Pt.',
        's.s.' => 'S.S.',
        's.sains.' => 'S.Sains.',
        's.si.' => 'S.Si.',
        's.sn.' => 'S.Sn.',
        's.sos.' => 'S.Sos.',
        's.stat.' => 'S.Stat.',
        's.t.' => 'S.T.',
        's.th.' => 'S.Th.',
        's.tp.' => 'S.TP.',

        // Magister
        'm.a.b.' => 'M.A.B.',
        'm.ag.' => 'M.Ag.',
        'm.ak.' => 'M.Ak.',
        'm.ars.' => 'M.Ars.',
        'm.e.' => 'M.E.',
        'm.farm.' => 'M.Farm.',
        'm.fil.' => 'M.Fil.',
        'm.h.' => 'M.H.',
        'm.han.' => 'M.Han.',
        'm.hum.' => 'M.Hum.',
        'm.i.kom.' => 'M.I.Kom.',
        'm.i.p.' => 'M.I.P.',
        'm.ked.' => 'M.Ked.',
        'm.kep.' => 'M.Kep.',
        'm.kes.' => 'M.Kes.',
        'm.k.m.' => 'M.K.M.',
        'm.kom.' => 'M.Kom.',
        'm.m.' => 'M.M.',
        'm.p.' => 'M.P.',
        'm.pd.' => 'M.Pd.',
        'm.psi.' => 'M.Psi.',
        'm.s.' => 'M.S.',
        'm.si.' => 'M.Si.',
        'm.sn.' => 'M.Sn.',
        'm.sos.' => 'M.Sos.',
        'm.stat.' => 'M.Stat.',
        'm.t.' => 'M.T.',
        'm.th.' => 'M.Th.',
        'm.tr.' => 'M.Tr.',
    ],
];
